export const types = {
  'GET_CENTER': 'GET_CENTER',
  'SET_CENTER': 'SET_CENTER',
  'SET_WATCH_ID': 'SET_WATCH_ID',
  'SET_INSIDE_FENCE':'SET_INSIDE_FENCE',
  'SET_FENCE': 'SET_FENCE',
  'SET_POLYGON': 'SET_POLYGON',
  'SET_BOUNDS': 'SET_BOUNDS',
  'SET_MARKERS': 'SET_MARKERS',
  'SET_PLACES': 'SET_PLACES',
  'SET_CENTER_SEARCH': 'SET_CENTER_SEARCH',
  'SET_MARKERS_SEARCH': 'SET_MARKERS_SEARCH',
  
};