export const types = {
  'GET_CENTER': 'GET_CENTER',
  'SET_CENTER': 'SET_CENTER',
  'SET_WATCH_ID': 'SET_WATCH_ID',
  'SET_INSIDE_FENCE':'SET_INSIDE_FENCE',
  'SET_FENCE': 'SET_FENCE',
  'SET_POLYGON': 'SET_POLYGON'
};